name: example
description: Demonstrates how to use the ant_media_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: "1.0.0+1"

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  flutter:
    sdk: flutter
  file: ^6.1.4
  get: ^4.6.1
  flutter_webrtc: ^0.10.8
  permission_handler: ^11.0.0
  shared_preferences: ^2.0.15
  shared_preferences_macos: ^2.0.4
  shared_preferences_web: ^2.0.4
  http: ^1.1.2
  path_provider: ^2.0.11
  path_provider_macos: ^2.0.6
  flutter_background: ^1.1.0

  ant_media_flutter:
    path: ../../

  cupertino_icons: ^1.0.2
  universal_io: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
